@startuml classification
!include https://raw.githubusercontent.com/guipatriota/dracula-plantuml-theme/v1.0.0/theme.puml
skinparam classAttributeIconSize 0

class ClassificationModel {
  +forward(x): torch.Tensor
  +calculate_per_class_metrics(predictions, labels): dict
  +_common_steps(batch, batch_idx, stage, logging): torch.Tensor
  +training_step(batch, batch_idx): torch.Tensor
  +validation_step(batch, batch_idx): None
  +test_step(batch, batch_idx): None
  +predict_step(batch, batch_idx): tuple[int, int]
  +configure_optimizers(): torch.optim.Optimizer
  +predict(img_path): dict
}

class ImageDataset {
  +setup(transform): None
  +train_dataloader(augmentation): data.DataLoader
  +val_dataloader(): data.DataLoader
  +test_dataloader(): data.DataLoader
  +loss_weights(): torch.Tensor
}

class TrainParams {
}

class PredictParams {
}

class ClassificationConfig {
}

@enduml
