train:
  model: resnet152
  model_weights: resnet152_default
  dataset: folder
  dataset_dir: /home/ingmar/Documents/repos/treespec/src/treespec/datasets/sauen/sauen_big_clean_nv6
  num_classes: 9
  use_ids: true
  epoch_count: 20
  batch_size: 5
  num_workers: 27
  learning_rate: 0.001
  loss_function: cross_entropy
  use_augmentations: false
  trained_model_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/models/
  train_augmentations: 
    - name: RandomVerticalFlip
      p: 0.1
    - name: RandomRotation
      degrees: 15
    - name: RandomResizedCrop
      size: [224, 224]
    - name: RandomPerspective
      distortion_scale: 0.3
      p: 0.3

extract:
  model: /home/ingmar/Documents/repos/treespec/src/treespec/io/models/X-101_RGB_60k.pth
  output_trees_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/pictures/
  video: /data/sauen_videos/3512a1/part1/corrected_VID_20231109_182711_00_001.mp4
  corrected: True
  predict_video_dest_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/videos/
  visualize: false
  predict: false
  mask: true

essen_dataset:
  attribute_path: /data/essen/cadastre/matched_output/matched_output
  original_color_images_path: /data/essen/MG4/2022-09-12_pano
  color_images_path: /home/ingmar/Documents/repos/treespec/src/treespec/io/pictures/color_4
  color_type: jpg
  original_seg_images_path: /data/essen/MG4/2022-09-12_2_seg
  segmentid_images_path: /home/ingmar/Documents/repos/treespec/src/treespec/io/pictures/segmentid_4
  seg_type: tif
  seg_output_type: png
  run: 4
  output_trees_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/pictures/trees_4
  mask: true
  filter: segmentid
  crop: false

matching:
  predicted_cadastre_path: /data/essen/cadastre/pred_cadastre_6-82/run82/run82
  cadastre_path: /data/essen/cadastre/Whole-Essen/cadastre_essen
  output_path: /data/essen/cadastre/matched_output_82/matched_output
  use_dbh_filter: False