train:
  model: resnet50
  model_weights: resnet50_default
  dataset: folder
  dataset_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/pictures/trees_70
  num_classes: 7
  use_ids: true
  epoch_count: 20
  batch_size: 5
  num_workers: 27
  learning_rate: 0.001
  loss_function: cross_entropy
  use_augmentations: false
  trained_model_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/models/
  train_augmentations: 
    - name: RandomVerticalFlip
      p: 0.1
    - name: RandomRotation
      degrees: 15
    - name: RandomResizedCrop
      size: [224, 224]
    - name: RandomPerspective
      distortion_scale: 0.3
      p: 0.3

extract:
  model: /home/ingmar/Documents/repos/treespec/src/treespec/io/models/X-101_RGB_60k.pth
  output_trees_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/pictures/
  video: /data/sauen_videos/3512a1/part1/corrected_VID_20231109_182711_00_001.mp4
  corrected: True
  predict_video_dest_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/videos/
  visualize: false
  predict: false
  mask: true

essen_dataset:
  attribute_path: /data/essen/inventory/matched_output_70/matched_output
  original_color_images_path: /data/essen/data/MG4/13.09.2022/panos
  color_images_path: /home/ingmar/Documents/repos/treespec/src/treespec/io/pictures/color_70
  color_type: jpg
  color_output_type: png
  original_id_images_path: /home/ingmar/Downloads/tree_filtering/output
  segmentid_images_path: /home/ingmar/Documents/repos/treespec/src/treespec/io/pictures/segmentid_70
  seg_type: tif
  seg_output_type: png
  original_sem_images_path: /home/ingmar/Downloads/tree_filtering/output
  semantic_images_path: /home/ingmar/Documents/repos/treespec/src/treespec/io/pictures/semantic_70
  sem_type: tif
  sem_output_type: png
  run: 70
  mask: bark
  output_trees_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/pictures/barks_70
  filter_id: segmentid
  filter_semantic: semanticclass
  crop: false
  pictures_extracted: false

matching:
  predicted_cadastre_path: /data/essen/inventory/pred_cadastre_6-82/run70/run70
  cadastre_path: /data/essen/inventory/Whole-Essen/cadastre_essen
  output_path: /data/essen/inventory/matched_output_70/matched_output
  use_dbh_filter: False