TrainParams:
  model: resnet152
  model_weights: resnet152_default
  dataset: sauen
  dataset_dir: /home/ingmar/Documents/repos/treespec/src/treespec/datasets/sauen/images/sauen_v2
  num_classes: 3
  epoch_count: 20
  batch_size: 5
  num_workers: 27
  learning_rate: 0.001
  loss_function: cross_entropy
  use_augmentations: false
  trained_model_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/models/

ExtractParams:
  model: /home/ingmar/Documents/repos/treespec/src/treespec/io/models/X-101_RGB_60k.pth
  output_trees_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/pictures/
  predict_video_dest_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/videos/
  visualize: false
  video: /data/training data/Sauen_Mapping_Dataset/cropped_20fps_Sauen.mp4
  corrected: True
