train:
  model: resnet152
  model_weights: resnet152_default
  dataset: folder
  dataset_dir: /home/ingmar/Documents/repos/treespec/src/treespec/datasets/sauen/sauen_big_clean
  num_classes: 9
  epoch_count: 20
  batch_size: 5
  num_workers: 27
  learning_rate: 0.001
  loss_function: cross_entropy
  use_augmentations: false
  trained_model_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/models/
  train_augmentations: 
    - name: RandomVerticalFlip
      p: 0.1
    - name: RandomRotation
      degrees: 15
    - name: RandomResizedCrop
      size: [224, 224]
    - name: RandomPerspective
      distortion_scale: 0.3
      p: 0.3

extract:
  model: /home/ingmar/Documents/repos/treespec/src/treespec/io/models/X-101_RGB_60k.pth
  output_trees_dir: /home/ingmar/Documents/repos/treespec/src/treespec/datasets/sauen/sauen_v6
  video: /data/sauen_videos/3507b2/VID_20231111_231220_00_010.mp4
  corrected: false
  predict_video_dest_dir: /home/ingmar/Documents/repos/treespec/src/treespec/io/videos/
  visualize: false
  predict: false
