"""Config file for treespec"""

MODEL_ARCHITECTURE = "resnet50"
MODEL_WEIGHTS = "DEFAULT"
NUM_CLASSES = 3
LEARNING_RATE = 0.001
BATCH_SIZE = 5
NUM_EPOCHS = 15
LOSS_FUNCTION = "CrossEntropyLoss"
LABEL_SMOOTHING = 0.1
OPTIMIZER = "Adam"
DATASET = "Sauen_Dataset"
