name: Code Quality Checks

on:
  workflow_call:
    inputs:
      update-coverage-badge:
        required: false
        default: false
        type: boolean

jobs:
  black:
    runs-on: ubuntu-latest
    container:
      image: vogelingmar/treespec
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v4
      - name: Analysing the code with black
        shell: bash
        run: |
          pwd
          ls
          source /workspace/venv/bin/activate
          cd /github/workspace/
          python -m pip install git+https://github.com/vogelingmar/treespec.git
          python -m pip install --upgrade .'[dev, docs]'
          black src --check --verbose --diff --color --line-length 120
          black test --check --verbose --diff --color --line-length 120
  mypy:
    runs-on: ubuntu-latest
    container:
      image: vogelingmar/treespec
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v4
      - name: Analysing the code with mypy
        shell: bash
        run: |
          source /workspace/venv/bin/activate
          cd /github/workspace/
          python -m pip install git+https://github.com/vogelingmar/treespec.git
          python -m pip install --upgrade .'[dev, docs]'
          mypy . --warn-unused-ignores --show-error-codes --no-incremental
  pylint:
    runs-on: ubuntu-latest
    container:
      image: vogelingmar/treespec
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v4
      - name: Analysing the code with pylint
        shell: bash
        run: |
          source /workspace/venv/bin/activate
          cd /github/workspace/
          python -m pip install git+https://github.com/vogelingmar/treespec.git
          python -m pip install --upgrade .'[dev, docs]'
          pylint src
          pylint test --disable duplicate-code --disable missing-function-docstring --disable too-many-positional-arguments
  test:
    runs-on: ubuntu-latest
    container:
      image: vogelingmar/treespec
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - name: Clean up potential remnants of past jobs
        uses: AutoModality/action-clean@v1.1.0
      - name: Checkout out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Executing tests
        shell: bash
        run: |
          source /workspace/venv/bin/activate
          cd /github/workspace/
          python -m pip install git+https://github.com/vogelingmar/treespec.git
          python -m pip install --upgrade .'[dev, docs]'
          # install CPU version of spconv (pointtorch depends on the cuda version but the CI runner has no GPU)
          python -m pip install --upgrade spconv
          coverage run -m pytest
          coverage-badge -f -o coverage.svg
      - name: Commit coverage badge
        if: ${{ inputs.update-coverage-badge == true }}
        shell: bash
        run: |
          cd /github/workspace/
          git config --global --add safe.directory $(realpath .)
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add coverage.svg
            git pull
            git commit -m "docs: update coverage badge [${{ github.event.pull_request.title }}] [skip-ci]"
            git push
          fi
