name: Build of Sphinx Documentation
on:
  pull_request:
    branches:
      - main

jobs:
  sphinx:
    name: Build documentation
    runs-on: ubuntu-latest
    container:
      image: vogelingmar/treespec
      volumes:
        - ${{ github.workspace }}:/github/workspace
    if: ${{ !startsWith(github.event.head_commit.message, 'Automated docs push:') && !startsWith(github.event.head_commit.message, 'Automated coverage batch push:')}}
    steps:
      - name: Clean up potential remnants of past jobs
        uses: AutoModality/action-clean@v1.1.0
      - name: Checkout out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Build sphinx documentation from docstrings
        shell: bash
        run: |
          source /workspace/venv/bin/activate
          cd /github/workspace/
          python -m pip install --upgrade .'[dev, docs]'
          sphinx-apidoc --force --module-first -t ./docs/source/apidoc_templates/ -o ./docs/source ./src
      - name: Commit and push documentation sources
        shell: bash
        run: |
          cd /github/workspace/
          git config --global --add safe.directory $(realpath .)
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add docs/source/*
            git pull
            git commit -m "docs: update docs [${{ github.event.pull_request.title }}] [skip-ci]"
            git push
          fi
